"""半開个人站构建入口。

    py -3 build.py                 构建到 dist/（不含草稿）
    py -3 build.py --drafts        连草稿一起构建，本地预览用
    py -3 build.py check           构建并检查：站内链接、外部链接、禁用词、待补项
        --offline                  跳过外部链接检查
        --blocklist PATH           禁用词清单（每行一个词）；也可用环境变量 SITE_BLOCKLIST
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import date
from pathlib import Path

from sitegen import checks, content, render

ROOT = Path(__file__).resolve().parent
MARKER = ".sitegen-build"


class BuildError(RuntimeError):
    pass


def _prepare_output(out: Path) -> None:
    """只清理本脚本生成过的目录（含标记文件），避免误删其他内容。"""
    if out.exists():
        # Vercel creates an empty output directory before invoking buildCommand.
        # Removing that empty scaffold is safe; never adopt a non-empty unmarked dir.
        if out.is_dir() and not any(out.iterdir()):
            out.rmdir()
        elif not (out / MARKER).exists():
            raise BuildError(f"{out} 已存在且不是本脚本生成的目录，拒绝覆盖")
        else:
            shutil.rmtree(out)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _write_version(out: Path) -> None:
    """Record which commit produced this build, so a live site can be traced to its source.

    Only environment variables are used: CI sets GIT_SHA/GITHUB_SHA and Vercel's Git integration
    sets VERCEL_GIT_COMMIT_SHA. A local `git rev-parse` is deliberately not used because this
    folder sits inside a larger repository whose commits are not the published history. For a
    Vercel CLI deploy pass it explicitly: `vercel deploy --prod --build-env GIT_SHA=<sha>`."""
    sha = (os.environ.get("GIT_SHA") or os.environ.get("VERCEL_GIT_COMMIT_SHA")
           or os.environ.get("GITHUB_SHA") or "unknown")
    info = {"service": "personal-site", "git_sha": sha}
    if os.environ.get("BUILD_TIME"):
        info["build_time"] = os.environ["BUILD_TIME"]
    _write(out / "version.json", json.dumps(info, ensure_ascii=False, indent=2) + "\n")


def _asset_href(out: Path, name: str) -> str:
    """站内脚本、样式的地址加上内容哈希：内容不变地址不变，改了就换新地址，才能放心长期缓存。"""
    return f"/{name}?v={hashlib.sha256((out / name).read_bytes()).hexdigest()[:10]}"


def build(root: Path = ROOT, out: Path | None = None, drafts: bool = False) -> Path:
    out = out or root / "dist"
    site = content.load_site(root / "content" / "site.json")
    projects = content.load_projects(root / "content" / "projects.json", root / "content" / "projects")
    pages = {p.slug: content.load_doc(root / "content" / "projects" / f"{p.slug}.md")
             for p in projects if p.link.type == "page"}
    all_posts = content.load_docs(root / "content" / "writing")
    posts = [d for d in all_posts if drafts or not d.draft]
    about = content.load_doc(root / "content" / "about.md")

    en_root = root / "content" / "en"
    en_site = content.load_site(en_root / "site.json")
    en_projects = content.load_projects(en_root / "projects.json", en_root / "projects")
    if [p.slug for p in projects] != [p.slug for p in en_projects]:
        raise BuildError("中英文 projects.json 必须包含相同顺序的 slug")
    en_pages = {p.slug: content.load_doc(en_root / "projects" / f"{p.slug}.md")
                for p in en_projects if p.link.type == "page"}
    en_all_posts = content.load_docs(en_root / "writing")
    en_posts = [d for d in en_all_posts if drafts or not d.draft]
    zh_public_slugs = [d.slug for d in all_posts if not d.draft]
    en_public_slugs = [d.slug for d in en_all_posts if not d.draft]
    if zh_public_slugs != en_public_slugs:
        raise BuildError("每篇已发布的中文文章都需要同 slug 的英文译文")
    en_about = content.load_doc(en_root / "about.md")

    _prepare_output(out)
    shutil.copytree(root / "static", out)
    (out / MARKER).write_text("generated by build.py\n", encoding="utf-8")

    css_href = _asset_href(out, "styles.css")
    boot_href = _asset_href(out, "boot.js")
    site_js_href = _asset_href(out, "site.js")
    zh_paths = {"/", "/about/"}
    en_paths = {"/", "/about/"}
    zh_paths.update(f"/projects/{p.slug}/" for p in projects if p.slug in pages)
    en_paths.update(f"/projects/{p.slug}/" for p in en_projects if p.slug in en_pages)
    if posts:
        zh_paths.add("/writing/")
        zh_paths.update(f"/writing/{d.slug}/" for d in posts)
    if en_posts:
        en_paths.add("/writing/")
        en_paths.update(f"/writing/{d.slug}/" for d in en_posts)

    locale_builds = (
        ("zh", "", site, projects, pages, posts, about, en_paths),
        ("en", "en", en_site, en_projects, en_pages, en_posts, en_about, zh_paths),
    )
    paths: list[str] = []
    for locale, directory, locale_site, locale_projects, locale_pages, locale_posts, locale_about, other_paths in locale_builds:
        locale_root = out / directory if directory else out
        ctx = render.Context(
            site=locale_site,
            show_writing=bool(locale_posts),
            css_href=css_href,
            year=date.today().year,
            locale=locale,
            other_paths=frozenset(other_paths),
            person_site=site,
            boot_href=boot_href,
            site_js_href=site_js_href,
        )
        locale_prefix = "/en" if locale == "en" else ""
        localize = lambda path: f"{locale_prefix}{path}" if locale_prefix else path
        _write(locale_root / "index.html", render.home(ctx, locale_projects, locale_posts))
        _write(locale_root / "about" / "index.html", render.about_page(ctx, locale_about))
        paths.extend([localize("/"), localize("/about/")])
        for project in locale_projects:
            if project.slug in locale_pages:
                route = f"/projects/{project.slug}/"
                _write(locale_root / "projects" / project.slug / "index.html",
                       render.project_page(ctx, project, locale_pages[project.slug]))
                paths.append(localize(route))
        if locale_posts:
            _write(locale_root / "writing" / "index.html", render.writing_index(ctx, locale_posts))
            paths.append(localize("/writing/"))
            for doc in locale_posts:
                _write(locale_root / "writing" / doc.slug / "index.html", render.post_page(ctx, doc))
                paths.append(localize(f"/writing/{doc.slug}/"))
            _write(locale_root / "feed.xml", render.atom(ctx, locale_posts))
    _write(out / "404.html", render.not_found(ctx))
    sitemap_ctx = render.Context(site=site, show_writing=bool(posts), css_href=css_href,
                                 year=date.today().year, locale="zh", other_paths=frozenset(en_paths), person_site=site,
                                 boot_href=boot_href, site_js_href=site_js_href)
    _write(out / "sitemap.xml", render.sitemap(sitemap_ctx, paths))
    _write(out / "robots.txt", render.robots(sitemap_ctx))
    _write_version(out)
    return out


def run_checks(out: Path, site: dict, *, offline: bool, blocklist: Path | None) -> int:
    pages = checks.scan_pages(out)
    errors = checks.check_internal(out, pages)
    if not offline:
        errors += checks.check_external(checks.external_links(pages))
    if blocklist:
        errors += checks.scan_blocklist(out, checks.load_blocklist(blocklist))
    notes = checks.placeholders(site)
    if not blocklist:
        notes.append("未提供禁用词清单（--blocklist 或 SITE_BLOCKLIST），本次没有扫描客户名等敏感词")
    if offline:
        notes.append("默认未联网检查外部链接；仅对可信内容使用 --check-external 开启")

    link_scope = "站内与外部链接问题" if not offline else "站内链接问题"
    print(f"页面 {len(pages)} 个；{link_scope}、禁用词命中共 {len(errors)} 条")
    for line in errors:
        print(f"  [错误] {line}")
    for line in notes:
        print(f"  [待补] {line}")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="半開个人站构建与检查")
    parser.add_argument("command", nargs="?", choices=["build", "check"], default="build")
    parser.add_argument("--drafts", action="store_true", help="包含 draft: true 的文章")
    parser.add_argument(
        "--check-external", action="store_true",
        help="联网检查外部链接；仅对可信内容开启",
    )
    parser.add_argument("--offline", action="store_true", help="兼容选项：跳过外部链接检查")
    parser.add_argument("--blocklist", type=Path, default=os.environ.get("SITE_BLOCKLIST") or None)
    args = parser.parse_args(argv)

    try:
        out = build(drafts=args.drafts)
    except (content.ContentError, BuildError) as exc:
        print(f"[失败] {exc}", file=sys.stderr)
        return 2
    print(f"已构建：{out}")
    if args.command == "check":
        blocklist = Path(args.blocklist) if args.blocklist else None
        if blocklist and not blocklist.exists():
            print(f"[失败] 禁用词清单不存在：{blocklist}", file=sys.stderr)
            return 2
        return run_checks(out, content.load_site(ROOT / "content" / "site.json"),
                          offline=not args.check_external or args.offline, blocklist=blocklist)
    return 0


if __name__ == "__main__":
    sys.exit(main())
