"""半開个人站构建入口。

    py -3 build.py                 构建到 dist/（不含草稿）
    py -3 build.py --drafts        连草稿一起构建，本地预览用
    py -3 build.py check           构建并检查：站内链接、外部链接、禁用词、待补项
        --offline                  跳过外部链接检查
        --blocklist PATH           禁用词清单（每行一个词）；也可用环境变量 SITE_BLOCKLIST
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import sys
from datetime import date
from pathlib import Path

from sitegen import checks, content, render

ROOT = Path(__file__).resolve().parent
MARKER = ".sitegen-build"


class BuildError(RuntimeError):
    pass


def _prepare_output(out: Path) -> None:
    """只清理本脚本生成过的目录（含标记文件），避免误删其他内容。"""
    if out.exists():
        # Vercel creates an empty output directory before invoking buildCommand.
        # Removing that empty scaffold is safe; never adopt a non-empty unmarked dir.
        if out.is_dir() and not any(out.iterdir()):
            out.rmdir()
        elif not (out / MARKER).exists():
            raise BuildError(f"{out} 已存在且不是本脚本生成的目录，拒绝覆盖")
        else:
            shutil.rmtree(out)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def build(root: Path = ROOT, out: Path | None = None, drafts: bool = False) -> Path:
    out = out or root / "dist"
    site = content.load_site(root / "content" / "site.json")
    projects = content.load_projects(root / "content" / "projects.json", root / "content" / "projects")
    pages = {p.slug: content.load_doc(root / "content" / "projects" / f"{p.slug}.md")
             for p in projects if p.link.type == "page"}
    posts = [d for d in content.load_docs(root / "content" / "writing") if drafts or not d.draft]
    about = content.load_doc(root / "content" / "about.md")

    _prepare_output(out)
    shutil.copytree(root / "static", out)
    (out / MARKER).write_text("generated by build.py\n", encoding="utf-8")

    css_version = hashlib.sha256((out / "styles.css").read_bytes()).hexdigest()[:10]
    ctx = render.Context(site=site, show_writing=bool(posts), css_href=f"/styles.css?v={css_version}",
                         year=date.today().year)

    paths = ["/", "/about/"]
    _write(out / "index.html", render.home(ctx, projects, posts))
    _write(out / "about" / "index.html", render.about_page(ctx, about))
    for p in projects:
        if p.slug in pages:
            _write(out / "projects" / p.slug / "index.html", render.project_page(ctx, p, pages[p.slug]))
            paths.append(f"/projects/{p.slug}/")
    if posts:
        _write(out / "writing" / "index.html", render.writing_index(ctx, posts))
        paths.append("/writing/")
        for d in posts:
            _write(out / "writing" / d.slug / "index.html", render.post_page(ctx, d))
            paths.append(f"/writing/{d.slug}/")
        _write(out / "feed.xml", render.atom(ctx, posts))
    _write(out / "404.html", render.not_found(ctx))
    _write(out / "sitemap.xml", render.sitemap(ctx, paths))
    _write(out / "robots.txt", render.robots(ctx))
    return out


def run_checks(out: Path, site: dict, *, offline: bool, blocklist: Path | None) -> int:
    pages = checks.scan_pages(out)
    errors = checks.check_internal(out, pages)
    if not offline:
        errors += checks.check_external(checks.external_links(pages))
    if blocklist:
        errors += checks.scan_blocklist(out, checks.load_blocklist(blocklist))
    notes = checks.placeholders(site)
    if not blocklist:
        notes.append("未提供禁用词清单（--blocklist 或 SITE_BLOCKLIST），本次没有扫描客户名等敏感词")
    if offline:
        notes.append("默认未联网检查外部链接；仅对可信内容使用 --check-external 开启")

    link_scope = "站内与外部链接问题" if not offline else "站内链接问题"
    print(f"页面 {len(pages)} 个；{link_scope}、禁用词命中共 {len(errors)} 条")
    for line in errors:
        print(f"  [错误] {line}")
    for line in notes:
        print(f"  [待补] {line}")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="半開个人站构建与检查")
    parser.add_argument("command", nargs="?", choices=["build", "check"], default="build")
    parser.add_argument("--drafts", action="store_true", help="包含 draft: true 的文章")
    parser.add_argument(
        "--check-external", action="store_true",
        help="联网检查外部链接；仅对可信内容开启",
    )
    parser.add_argument("--offline", action="store_true", help="兼容选项：跳过外部链接检查")
    parser.add_argument("--blocklist", type=Path, default=os.environ.get("SITE_BLOCKLIST") or None)
    args = parser.parse_args(argv)

    try:
        out = build(drafts=args.drafts)
    except (content.ContentError, BuildError) as exc:
        print(f"[失败] {exc}", file=sys.stderr)
        return 2
    print(f"已构建：{out}")
    if args.command == "check":
        blocklist = Path(args.blocklist) if args.blocklist else None
        if blocklist and not blocklist.exists():
            print(f"[失败] 禁用词清单不存在：{blocklist}", file=sys.stderr)
            return 2
        return run_checks(out, content.load_site(ROOT / "content" / "site.json"),
                          offline=not args.check_external or args.offline, blocklist=blocklist)
    return 0


if __name__ == "__main__":
    sys.exit(main())
